export default [
    {
      path:'/',
      name:'LayOut',
      component:()=>import('../views/LayOut.vue'),
      redirect:'/index',
      children:[{
          path:'/index',
          name:'index',
          component:()=>import('../views/index/HomeIndex')
      },
      {
        path:'/orders/list',
        name:'orders',
        component:()=>import('../views/orders/orderList'),
        meta:{bread:["订单管理","订单列表"]}
      },
      {
        path:'/waybill/list',
        name:'waybill',
        meta:{bread:["运单管理","运单列表"],keepAlive:true},
        component:()=>import('../views/waybill/WayBill')
      },
      {
        path:'/waybill/list/detail',
        name:'waybilldetail',
        meta:{bread:["运单管理","运单列表","运单详情"]},
        component:()=>import('../views/waybill/WayBilldetail')
      },
      {
        path:'/waybill/in',
        name:'waybillinput',
        meta:{bread:["运单管理","运单录入"]},
        component:()=>import('../views/waybill/WaybillInput')
      },
      {
        path:'/depart/data',
        name:'departdata',
        meta:{bread:["发车管理","发车数据单"]},
        component:()=>import('../views/depart/DepartData')
      }]
    },
    {
      path:'/login',
      name:'login',
      component:()=>import('../views/LoginRegistry.vue')
    },
  ]